### ISSUE TITLE
NullPointerException during saving of Scatterplot

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#122]
Saving Scatterplot data is triggering the following `NullPointerException` in the logs on `aws-spatial-prod`:

```==> /var/log/tomcat7/catalina.out <==
2019-03-13 10:06:55:193 SpatialUtils [INFO] sample time for 5 layers and 3 coordinates: get response=5122ms, write response=6ms
2019-03-13 10:06:55:469 Scatterplot [ERROR] failed to save scatterplot data: /data/spatial-data/public/24719/data.xml
java.lang.NullPointerException
	at au.org.ala.scatterplot.Scatterplot.save(Scatterplot.java:1491)
	at au.org.ala.scatterplot.Scatterplot$save$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at au.org.ala.spatial.process.ScatterplotCreate.start(ScatterplotCreate.groovy:77)
	at au.org.ala.spatial.process.ScatterplotCreate$start.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at au.org.ala.spatial.process.Maxent$start.call(Unknown Source)
	at au.org.ala.spatial.slave.TaskService$TaskThread.run(TaskService.groovy:299)
```

**Comment by ansell** [comment]
There is a similar, but slightly different location `NullPointerException` in the following stacktrace, with the file not found error possibly being the trigger for the NPE:

```
==> /var/log/tomcat7/catalina.out <==
2019-03-14 13:22:13:263 Scatterplot [ERROR] error reading scatterplot from disk
java.io.FileNotFoundException: File '/data/spatial-data/public/28842/data.xml' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748)
	at au.org.ala.scatterplot.Scatterplot.load(Scatterplot.java:1513)
	at au.org.ala.scatterplot.Scatterplot$load$5.call(Unknown Source)
	at au.org.ala.spatial.process.ScatterplotDraw.start(ScatterplotDraw.groovy:45)
	at au.org.ala.spatial.process.ScatterplotDraw$start.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at au.org.ala.spatial.process.ScatterplotCreate$start.call(Unknown Source)
	at au.org.ala.spatial.slave.TaskService$TaskThread.run(TaskService.groovy:299)
2019-03-14 13:22:13.263 ERROR --- [   Thread-40490] au.org.ala.spatial.slave.TaskService     : error running request: 28853

java.lang.NullPointerException: Cannot invoke method getScatterplotStyleDTO() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at au.org.ala.spatial.process.ScatterplotDraw.start(ScatterplotDraw.groovy:47)
	at au.org.ala.spatial.process.ScatterplotDraw$start.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at au.org.ala.spatial.process.ScatterplotCreate$start.call(Unknown Source)
	at au.org.ala.spatial.slave.TaskService$TaskThread.run(TaskService.groovy:299)
```

**Comment by adam-collins** [comment]
Fixed
