### ISSUE TITLE
NullPointerException during Maxent task

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#150]
The following NullPointerException is in the log file for a failed Maxent job that a Twitter user reported:

```
[SPATIAL-SERVICE] 11:09:05.479 a.o.a.s.s.TaskService : error running request: 959866
java.lang.NullPointerException: null
        at au.org.ala.layers.intersect.Grid.getGrid(Grid.java:169)
        at au.org.ala.layers.intersect.Grid$getGrid.call(Unknown Source)
        at au.org.ala.spatial.process.SlaveProcess.getLayerExtents(SlaveProcess.groovy:481)
        at au.org.ala.spatial.process.SlaveProcess.cutGrid(SlaveProcess.groovy:392)
        at au.org.ala.spatial.process.SlaveProcess$cutGrid$8.callCurrent(Unknown Source)
        at au.org.ala.spatial.process.Maxent.start(Maxent.groovy:64)
        at au.org.ala.spatial.process.Maxent$start.call(Unknown Source)
        at au.org.ala.spatial.slave.TaskService$TaskThread.run(TaskService.groovy:339)
```

There are a few options for a NullPointerException on that line:

https://github.com/AtlasOfLivingAustralia/layers-store/blob/07d187673411b8b96292eeb2a8c42c5762352f8a/src/main/java/au/org/ala/layers/intersect/Grid.java#L169

**Comment by ansell** [comment]
The following code in this stacktrace also needs work to productionise it:

https://github.com/AtlasOfLivingAustralia/spatial-service/blob/ecbffe9f47fdc0bba478866595d5919a697acef2/src/main/groovy/au/org/ala/spatial/process/SlaveProcess.groovy#L519-L521

https://github.com/AtlasOfLivingAustralia/spatial-service/blob/ecbffe9f47fdc0bba478866595d5919a697acef2/src/main/groovy/au/org/ala/spatial/process/SlaveProcess.groovy#L528

**Comment by qifeng-bai** [comment]
Error is captured :
https://github.com/AtlasOfLivingAustralia/spatial-service/commit/ce020d3bcd06e40a14895c52cabb180bf5a469ac
