### ISSUE TITLE
MERIT is no longer able to upload shapefiles consisting of Points or Lines

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/spatial-service#151]
MERIT used to be able to create sites from uploaded shapefiles with a geometry type of Point or MultiPoint.  This is now failing due to an attempt to correct the geometry:
[SPATIAL-SERVICE] 11:21:00.548 a.o.a.l.ShapesController : Error processsing shapefile feature request

java.lang.ArrayIndexOutOfBoundsException: 0
        at au.org.ala.spatial.util.GeomMakeValid.LWGEOM_GEOS_nodeLines(GeomMakeValid.java:317)
        at au.org.ala.spatial.util.GeomMakeValid.makeValid(GeomMakeValid.java:189)
        at au.org.ala.spatial.util.GeomMakeValid$makeValid.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at au.org.ala.spatial.util.GeomMakeValid$makeValid.call(Unknown Source)
        at au.org.ala.layers.ShapesController.fixWkt(ShapesController.groovy:749)
        at au.org.ala.layers.ShapesController.processShapeFileFeatureRequest(ShapesController.groovy:445)

To reproduce:
[TestPointShapefile.zip](https://github.com/AtlasOfLivingAustralia/spatial-service/files/5265019/TestPointShapefile.zip)

Take the attached shapefile (created in QGIS) and upload it into any project in the MERIT test environment.
The initial upload works correctly (WS call to /shape/upload/shp) but subsequent calls to (/shape/upload/shp/shapefile id/featureId now fails with the Exception above.

**Comment by chrisala** [comment]
It has also been reported that Shapefiles with a linestring (and presumably multilinestring) data type are failing for the same reason.
