### ISSUE TITLE
OutOfMemoryError during AreaReportPDF constructor

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#95]
An ``OutOfMemoryError`` crashed the nectar-spatial-staging tomcat server with the following traces in the logs, appearing to have multiple threads building ``StringBuffer`` objects during the AreaReportPDF constructor:

```
PROGRESS: Getting information: species list for lifeform Algae 0.0
PROGRESS: Getting information: species list for lifeform Algae 0.0
PROGRESS: Getting information: species list for lifeform Algae 0.0
PROGRESS: Getting information: species list for lifeform Amphibians 0.0
PROGRESS: Getting information: species list for lifeform Amphibians 0.0
PROGRESS: Getting information: species list for lifeform Amphibians 0.0
PROGRESS: Getting information: species list for lifeform Angiosperms 0.0
PROGRESS: Getting information: species list for lifeform Angiosperms 0.0
PROGRESS: Getting information: species list for lifeform Angiosperms 0.0
PROGRESS: Getting information: species list for lifeform Animals 0.0
PROGRESS: Getting information: species list for lifeform Animals 0.0
PROGRESS: Getting information: species list for lifeform Animals 0.0
PROGRESS: Getting information: species list for lifeform Arthropods 0.0
PROGRESS: Getting information: species list for lifeform Arthropods 0.0
PROGRESS: Getting information: species list for lifeform Arthropods 0.0
PROGRESS: Getting information: species list for lifeform Bacteria 0.0
PROGRESS: Getting information: species list for lifeform Bacteria 0.0
PROGRESS: Getting information: species list for lifeform Bacteria 0.0
PROGRESS: Getting information: species list for lifeform Birds 0.0
PROGRESS: Getting information: species list for lifeform Birds 0.0
PROGRESS: Getting information: species list for lifeform Birds 0.0
PROGRESS: Getting information: species list for lifeform Bryophytes 0.0
PROGRESS: Getting information: species list for lifeform Bryophytes 0.0
PROGRESS: Getting information: species list for lifeform Bryophytes 0.0
PROGRESS: Getting information: species list for lifeform Chromista 0.0
PROGRESS: Getting information: species list for lifeform Chromista 0.0
PROGRESS: Getting information: species list for lifeform Chromista 0.0
PROGRESS: Getting information: species list for lifeform Crustaceans 0.0
PROGRESS: Getting information: species list for lifeform Crustaceans 0.0
PROGRESS: Getting information: species list for lifeform Crustaceans 0.0
PROGRESS: Getting information: species list for lifeform Dicots 0.0
PROGRESS: Getting information: species list for lifeform Dicots 0.0
PROGRESS: Getting information: species list for lifeform Dicots 0.0
PROGRESS: Getting information: species list for lifeform FernsAndAllies 0.0
PROGRESS: Getting information: species list for lifeform FernsAndAllies 0.0
PROGRESS: Getting information: species list for lifeform FernsAndAllies 0.0
PROGRESS: Getting information: species list for lifeform Fishes 0.0
PROGRESS: Getting information: species list for lifeform Fishes 0.0
PROGRESS: Getting information: species list for lifeform Fishes 0.0
PROGRESS: Getting information: species list for lifeform Fungi 0.0
PROGRESS: Getting information: species list for lifeform Fungi 0.0
PROGRESS: Getting information: species list for lifeform Fungi 0.0
PROGRESS: Getting information: species list for lifeform Gymnosperms 0.0
PROGRESS: Getting information: species list for lifeform Gymnosperms 0.0
PROGRESS: Getting information: species list for lifeform Gymnosperms 0.0
PROGRESS: Getting information: species list for lifeform Insects 0.0
PROGRESS: Getting information: species list for lifeform Insects 0.0
PROGRESS: Getting information: species list for lifeform Insects 0.0
PROGRESS: Getting information: species list for lifeform Mammals 0.0
PROGRESS: Getting information: species list for lifeform Mammals 0.0
PROGRESS: Getting information: species list for lifeform Mammals 0.0
PROGRESS: Getting information: species list for lifeform Molluscs 0.0
PROGRESS: Getting information: species list for lifeform Molluscs 0.0
PROGRESS: Getting information: species list for lifeform Molluscs 0.0
PROGRESS: Getting information: species list for lifeform Monocots 0.0
PROGRESS: Getting information: species list for lifeform Monocots 0.0
PROGRESS: Getting information: species list for lifeform Monocots 0.0
PROGRESS: Getting information: species list for lifeform Plants 0.0
PROGRESS: Getting information: species list for lifeform Plants 0.0
PROGRESS: Getting information: species list for lifeform Plants 0.0
PROGRESS: Getting information: species list for lifeform Protozoa 0.0
PROGRESS: Getting information: species list for lifeform Protozoa 0.0
PROGRESS: Getting information: species list for lifeform Protozoa 0.0
PROGRESS: Getting information: species list for lifeform Reptiles 0.0
PROGRESS: Getting information: species list for lifeform Reptiles 0.0
PROGRESS: Getting information: species list for lifeform Reptiles 0.0
PROGRESS: Getting information: threatened species list 0.0
PROGRESS: Getting information: threatened species list 0.0
PROGRESS: Getting information: threatened species list 0.0
PROGRESS: Getting information: iconic species list 0.0
PROGRESS: Getting information: iconic species list 0.0
PROGRESS: Getting information: iconic species list 0.0
PROGRESS: Getting information: migratory species list 0.0
PROGRESS: Getting information: migratory species list 0.0
PROGRESS: Getting information: migratory species list 0.0
PROGRESS: Getting information: invasive species list 0.0
PROGRESS: Getting information: invasive species list 0.0
PROGRESS: Getting information: invasive species list 0.0
PROGRESS: Getting information: saving 0.0
PROGRESS: Getting information: saving 0.0
PROGRESS: Getting information: saving 0.0
Exception in thread "Thread-18" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
	at java.lang.StringBuffer.append(StringBuffer.java:381)
	at org.json.simple.JSONValue.escape(JSONValue.java:266)
	at org.json.simple.JSONValue.escape(JSONValue.java:219)
	at org.json.simple.JSONValue.toJSONString(JSONValue.java:176)
	at org.json.simple.JSONObject.toJSONString(JSONObject.java:119)
	at org.json.simple.JSONObject.toJSONString(JSONObject.java:101)
	at org.json.simple.JSONValue.toJSONString(JSONValue.java:202)
	at au.org.ala.spatial.util.AreaReportPDF.init(AreaReportPDF.java:717)
	at au.org.ala.spatial.util.AreaReportPDF.<init>(AreaReportPDF.java:137)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at au.org.ala.spatial.process.AreaReport.start(AreaReport.groovy:51)
	at au.org.ala.spatial.process.AreaReport$start.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at au.org.ala.spatial.slave.TaskService$TaskThread.run(TaskService.groovy:265)
Exception in thread "Thread-17" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuffer.append(StringBuffer.java:270)
	at org.json.simple.JSONValue.toJSONString(JSONValue.java:176)
	at org.json.simple.JSONObject.toJSONString(JSONObject.java:119)
	at org.json.simple.JSONObject.toJSONString(JSONObject.java:101)
	at org.json.simple.JSONValue.toJSONString(JSONValue.java:202)
	at au.org.ala.spatial.util.AreaReportPDF.init(AreaReportPDF.java:717)
	at au.org.ala.spatial.util.AreaReportPDF.<init>(AreaReportPDF.java:137)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at au.org.ala.spatial.process.AreaReport.start(AreaReport.groovy:51)
	at au.org.ala.spatial.process.AreaReport$start.call(Unknown Source)
	at au.org.ala.spatial.slave.TaskService$TaskThread.run(TaskService.groovy:265)
Exception in thread "Thread-19" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.StringBuffer.toString(StringBuffer.java:669)
	at org.json.simple.JSONObject.toJSONString(JSONObject.java:121)
	at org.json.simple.JSONObject.toJSONString(JSONObject.java:101)
	at org.json.simple.JSONValue.toJSONString(JSONValue.java:202)
	at au.org.ala.spatial.util.AreaReportPDF.init(AreaReportPDF.java:717)
	at au.org.ala.spatial.util.AreaReportPDF.<init>(AreaReportPDF.java:137)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at au.org.ala.spatial.process.AreaReport.start(AreaReport.groovy:51)
	at au.org.ala.spatial.process.AreaReport$start$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at au.org.ala.spatial.slave.TaskService$TaskThread.run(TaskService.groovy:265)
```

**Comment by ansell** [comment]
The descriptions for the three concurrent AreaReport tasks in the task scheduler that may have caused the issue are:

```
Message | Url | Name | Tag | Created | Status | History 
-- | -- | -- | -- | -- | -- | -- | 
running |   | AreaReport | null | 2018-05-04 15:11:04 AEST | 0 | {1526348788298=Getting information: e,  1526348786553=Getting information: c, 1526348792398=Getting information:  images for map of layer cl1052, 1526348824799=Getting information:  making map of lifeform Chromista, 1526348793368=Getting information:  making map of area, 1526347107959=Getting information: images for map of  lifeform Fungi, 1526347107958=Getting information: images for map of  lifeform Angiosperms, 1526348792399=Getting information: making map of  cl1052, 1526347117642=Getting information: species count  geospatial_kosher=true, 1526347133845=Getting information: making map of  lifeform Crustaceans, 1526348799305=Getting information: making  invasive species, 1526348820397=Getting information: making map of  lifeform Bacteria, 1526348829600=Getting information: making map of  lifeform FernsAndAllies, 1526347108001=Getting information: images for  map of threatened species, 1526348838952=Getting information: making map  of lifeform Molluscs, 1526347108002=Getting information: threatened  species, 1526348816129=Getting information: making map of lifeform  Arthropods, 1526347108008=Getting information: occurrences,  1526348838155=Getting information: making map of lifeform Mammals,  1526347126754=Getting information: making map of lifeform Animals,  1526348833980=Getting information: making map of lifeform Fungi,  1526347108004=Getting information: distribution areas,  1526347127764=Getting information: making map of lifeform Arthropods,  1526347128699=Getting information: making map of lifeform Bacteria,  1526347141158=Getting information: making map of lifeform Mammals,  1526348825995=Getting information: making map of lifeform Crustaceans,  1526347117132=Getting information: making occurrences,  1526347123778=Getting information: making map of lifeform Algae,  1526347107904=Getting information, 1526347115079=Getting information:  Journalmap, 1526348809444=Getting information: making map of lifeform  Animals, 1526347138577=Getting information: making map of lifeform  Gymnosperms, 1526347135831=Getting information: making map of lifeform  FernsAndAllies, 1526347116169=Getting information: making map of area  overview, 1526347133056=Getting information: making map of lifeform  Chromista, 1526347108110=Getting information: endemic species count,  1526347112966=Getting information: e, 1526348835471=Getting information:  making map of lifeform Gymnosperms, 1526347139904=Getting information:  making map of lifeform Insects, 1526348798302=Getting information:  making migratory species, 1526348832326=Getting information: making map  of lifeform Fishes, 1526347129553=Getting information: making map of  lifeform Birds, 1526348797299=Getting information: making iconic  species, 1526348837015=Getting information: making map of lifeform  Insects, 1526348791203=Getting information: making map of cl1053,  1526348800685=Getting information: making map of lifeform Algae,  1526348786451=Getting information: occurrences count  geospatial_kosher=true, 1526347112091=Getting information: occurrences  count geospatial_kosher=true, 1526348794116=Getting information: making  map of area overview, 1526347134716=Getting information: making map of  lifeform Dicots, 1526348786213=Getting information: species list,  1526348823282=Getting information: making map of lifeform Bryophytes,  1526348840261=Getting information: making map of lifeform Monocots,  1526347119961=Getting information: making migratory species,  1526348786172=Getting information: images for map of map,  1526347141932=Getting information: making map of lifeform Molluscs,  1526348790829=Getting information: Journalmap, 1526348806390=Getting  information: making map of lifeform Angiosperms, 1526347137718=Getting  information: making map of lifeform Fungi, 1526347145658=Getting  information: making map of lifeform Reptiles, 1526348786216=Getting  information: occurrences, 1526347144844=Getting information: making map  of lifeform Protozoa, 1526347124672=Getting information: making map of  lifeform Amphibians, 1526348784316=Getting information,  1526347125733=Getting information: making map of lifeform Angiosperms,  1526348786186=Getting information: images for map of lifeform Mammals,  1526348786185=Getting information: images for map of lifeform Chromista,  1526348844272=Getting information: making map of lifeform Plants,  1526347118286=Getting information: making threatened species,  1526348786188=Getting information: making map of cl1918,  1526348786187=Getting information: images for map of iconic species,  1526348796546=Getting information: making threatened species,  1526348827836=Getting information: making map of lifeform Dicots,  1526347114287=Getting information: making map of cl1052,  1526347119217=Getting information: making iconic species,  1526348802272=Getting information: making map of lifeform Amphibians,  1526347130369=Getting information: making map of lifeform Bryophytes,  1526347115413=Getting information: making map of area,  1526348846653=Getting information: making map of lifeform Reptiles,  1526348786184=Getting information: images for map of lifeform  Angiosperms, 1526348821694=Getting information: making map of lifeform  Birds, 1526348786260=Getting information: threatened species,  1526348845521=Getting information: making map of lifeform Protozoa,  1526347108057=Getting information: species list, 1526347136862=Getting  information: making map of lifeform Fishes, 1526348798046=Getting  information: species count geospatial_kosher=true, 1526347108490=Getting  information: c, 1526347143028=Getting information: making map of  lifeform Monocots, 1526347143985=Getting information: making map of  lifeform Plants, 1526348795531=Getting information: making occurrences,  1526347107960=Getting information: images for map of lifeform Insects,  1526347109303=Getting information: making map of cl1053,  1526347122985=Getting information: making invasive species,  1526347107962=Getting information: images for map of lifeform Protozoa,  1526347107961=Getting information: images for map of lifeform Molluscs,  1526347109302=Getting information: images for map of layer cl1053} | re-run task | cancel
running |   | AreaReport | null | 2018-05-04 15:08:00 AEST | 0 | {1526347125746=Getting information: making map of  lifeform Angiosperms, 1526348802521=Getting information: making map of  lifeform Amphibians, 1526348823103=Getting information: making map of  lifeform Bryophytes, 1526348788298=Getting information: e,  1526348790692=Getting information: making map of cl1053,  1526348809319=Getting information: making map of lifeform Animals,  1526347137011=Getting information: making map of lifeform Fishes,  1526348838719=Getting information: making map of lifeform Molluscs,  1526348821401=Getting information: making map of lifeform Birds,  1526347130694=Getting information: making map of lifeform Bryophytes,  1526347116510=Getting information: making occurrences,  1526347133169=Getting information: making map of lifeform Chromista,  1526348844807=Getting information: making map of lifeform Protozoa,  1526348798257=Getting information: making migratory species,  1526348846627=Getting information: making map of lifeform Reptiles,  1526347108480=Getting information: c, 1526347129543=Getting information:  making map of lifeform Birds, 1526348834118=Getting information: making  map of lifeform Gymnosperms, 1526348786479=Getting information: c,  1526347127688=Getting information: making map of lifeform Arthropods,  1526348797287=Getting information: making iconic species,  1526348832134=Getting information: making map of lifeform Fungi,  1526347119550=Getting information: making migratory species,  1526348800755=Getting information: making map of lifeform Algae,  1526347123539=Getting information: making map of lifeform Algae,  1526347113253=Getting information: making map of cl1052,  1526347135957=Getting information: making map of lifeform  FernsAndAllies, 1526347134822=Getting information: making map of  lifeform Dicots, 1526348824220=Getting information: making map of  lifeform Chromista, 1526347138734=Getting information: making map of  lifeform Gymnosperms, 1526347134023=Getting information: making map of  lifeform Crustaceans, 1526347108074=Getting information: images for map  of layer cl1918, 1526347108075=Getting information: making map of  cl1918, 1526347114901=Getting information: making map of area,  1526347112527=Getting information: e, 1526348786175=Getting information:  images for map of lifeform Crustaceans, 1526348828537=Getting  information: making map of lifeform FernsAndAllies,  1526348786174=Getting information: images for map of lifeform Birds,  1526348825587=Getting information: making map of lifeform Crustaceans,  1526348786177=Getting information: images for map of lifeform Mammals,  1526348786176=Getting information: images for map of lifeform Fungi,  1526348791721=Getting information: making map of cl1052,  1526348786179=Getting information: images for map of migratory species,  1526348786178=Getting information: images for map of lifeform Protozoa,  1526347107937=Getting information, 1526348806422=Getting information:  making map of lifeform Angiosperms, 1526347118233=Getting information:  species count geospatial_kosher=true, 1526348786173=Getting information:  images for map of lifeform Angiosperms, 1526348793307=Getting  information: making map of area, 1526348786172=Getting information:  occurrences, 1526348786370=Getting information: occurrences count  geospatial_kosher=true, 1526347108067=Getting information: images for  map of lifeform Fungi, 1526347108068=Getting information: images for map  of lifeform Monocots, 1526347108065=Getting information: images for map  of lifeform Animals, 1526347108066=Getting information: images for map  of lifeform Chromista, 1526347108064=Getting information: images for map  of map, 1526347117509=Getting information: making threatened species,  1526347109195=Getting information: making map of cl1053,  1526347114918=Getting information: Journalmap, 1526348784316=Getting  information, 1526347108069=Getting information: images for map of  threatened species, 1526347140201=Getting information: making map of  lifeform Insects, 1526348791213=Getting information: Journalmap,  1526348795978=Getting information: species count geospatial_kosher=true,  1526347124646=Getting information: making map of lifeform Amphibians,  1526348826549=Getting information: making map of lifeform Dicots,  1526348830006=Getting information: making map of lifeform Fishes,  1526347126706=Getting information: making map of lifeform Animals,  1526347118645=Getting information: making iconic species,  1526348840032=Getting information: making map of lifeform Monocots,  1526348786180=Getting information: making map of cl1918,  1526347112463=Getting information: occurrences count  geospatial_kosher=true, 1526347137862=Getting information: making map of  lifeform Fungi, 1526348815909=Getting information: making map of  lifeform Arthropods, 1526348796381=Getting information: making  threatened species, 1526348819949=Getting information: making map of  lifeform Bacteria, 1526348843507=Getting information: making map of  lifeform Plants, 1526348795170=Getting information: making occurrences,  1526348837039=Getting information: making map of lifeform Mammals,  1526347108010=Getting information: species list, 1526348799333=Getting  information: making invasive species, 1526347115619=Getting information:  making map of area overview, 1526348835295=Getting information: making  map of lifeform Insects, 1526347120645=Getting information: making  invasive species, 1526348794045=Getting information: making map of area  overview, 1526347128525=Getting information: making map of lifeform  Bacteria, 1526347108058=Getting information: endemic species count} | re-run task | cancel
running |   | AreaReport | null | 2018-05-04 15:06:43 AEST | 0 | {1526348786199=Getting information: images for map  of lifeform Chromista, 1526348788297=Getting information: e,  1526348821041=Getting information: making map of lifeform Bacteria,  1526348786198=Getting information: images for map of lifeform  Angiosperms, 1526348796317=Getting information: making threatened  species, 1526348819165=Getting information: making map of lifeform  Arthropods, 1526347105339=Getting information: images for map of map,  1526348807217=Getting information: making map of lifeform Angiosperms,  1526348799426=Getting information: making invasive species,  1526348844720=Getting information: making map of lifeform Protozoa,  1526347117206=Getting information: making iconic species,  1526347133522=Getting information: making map of lifeform Dicots,  1526348828116=Getting information: making map of lifeform Dicots,  1526347136557=Getting information: making map of lifeform Fungi,  1526347144708=Getting information: making map of lifeform Reptiles,  1526347112315=Getting information: making map of area,  1526348812367=Getting information: making map of lifeform Animals,  1526347112318=Getting information: e, 1526348798336=Getting information:  making migratory species, 1526347127486=Getting information: making map  of lifeform Bacteria, 1526347105972=Getting information: c,  1526348831520=Getting information: making map of lifeform Fishes,  1526347142800=Getting information: making map of lifeform Plants,  1526347123532=Getting information: making map of lifeform Amphibians,  1526348790344=Getting information: making map of cl1053,  1526348793732=Getting information: making map of area overview,  1526347129956=Getting information: making map of lifeform Chromista,  1526348800794=Getting information: making map of lifeform Algae,  1526348786201=Getting information: endemic species count,  1526348786200=Getting information: images for map of lifeform Fishes,  1526348792004=Getting information: making map of cl1052,  1526348786488=Getting information: c, 1526347119514=Getting information:  making invasive species, 1526348837938=Getting information: making map  of lifeform Mammals, 1526347141819=Getting information: making map of  lifeform Monocots, 1526348840250=Getting information: making map of  lifeform Monocots, 1526347137489=Getting information: making map of  lifeform Gymnosperms, 1526347132686=Getting information: making map of  lifeform Crustaceans, 1526348823496=Getting information: making map of  lifeform Bryophytes, 1526348846115=Getting information: making map of  lifeform Reptiles, 1526348834583=Getting information: making map of  lifeform Gymnosperms, 1526347105360=Getting information: images for map  of iconic species, 1526347112323=Getting information: occurrences count  geospatial_kosher=true, 1526348836244=Getting information: making map of  lifeform Insects, 1526347105362=Getting information: images for map of  layer cl1918, 1526347129111=Getting information: making map of lifeform  Bryophytes, 1526347118628=Getting information: making migratory species,  1526348786205=Getting information: images for map of lifeform Plants,  1526348839154=Getting information: making map of lifeform Molluscs,  1526348786204=Getting information: images for map of lifeform  Gymnosperms, 1526348786369=Getting information: occurrences count  geospatial_kosher=true, 1526348786207=Getting information: making map of  cl1918, 1526347125671=Getting information: making map of lifeform  Animals, 1526348786206=Getting information: images for map of migratory  species, 1526347105363=Getting information: making map of cl1918,  1526348797296=Getting information: making iconic species,  1526348795127=Getting information: making occurrences,  1526347124639=Getting information: making map of lifeform Angiosperms,  1526348843499=Getting information: making map of lifeform Plants,  1526348822039=Getting information: making map of lifeform Birds,  1526347114153=Getting information: making map of area overview,  1526347116099=Getting information: Journalmap, 1526348824691=Getting  information: making map of lifeform Chromista, 1526347138400=Getting  information: making map of lifeform Insects, 1526347115366=Getting  information: making occurrences, 1526348790714=Getting information:  Journalmap, 1526348826113=Getting information: making map of lifeform  Crustaceans, 1526347105350=Getting information: images for map of  lifeform Crustaceans, 1526348798793=Getting information: species count  geospatial_kosher=true, 1526347108382=Getting information: making map of  cl1052, 1526347116419=Getting information: making threatened species,  1526348793067=Getting information: making map of area,  1526347105358=Getting information: images for map of lifeform  FernsAndAllies, 1526347105359=Getting information: images for map of  lifeform Protozoa, 1526347126573=Getting information: making map of  lifeform Arthropods, 1526348784316=Getting information,  1526347140962=Getting information: making map of lifeform Molluscs,  1526348803838=Getting information: making map of lifeform Amphibians,  1526347143830=Getting information: making map of lifeform Protozoa,  1526347139684=Getting information: making map of lifeform Mammals,  1526348829456=Getting information: making map of lifeform  FernsAndAllies, 1526347103281=Getting information, 1526347134443=Getting  information: making map of lifeform FernsAndAllies,  1526347135530=Getting information: making map of lifeform Fishes,  1526347105340=Getting information: images for map of lifeform Birds,  1526347128242=Getting information: making map of lifeform Birds,  1526347120645=Getting information: making map of lifeform Algae,  1526348832545=Getting information: making map of lifeform Fungi,  1526347105347=Getting information: threatened species,  1526347114807=Getting information: species count geospatial_kosher=true,  1526347105341=Getting information: images for map of lifeform  Chromista, 1526347107289=Getting information: making map of cl1053,  1526347105342=Getting information: species count, 1526347105343=Getting  information: species list, 1526347105344=Getting information: endemic  species count}
```

**Comment by Rita-C** [comment]
Similar OutOfMemoryError on beta 2018-06-28 11:33:43.855
```
Exception in thread "Thread-1031" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at au.org.ala.layers.util.Occurrences.getOccurrences(Occurrences.java:101)
	at au.org.ala.scatterplot.Scatterplot.resample(Scatterplot.java:867)
	at au.org.ala.scatterplot.Scatterplot.buildScatterplot(Scatterplot.java:182)
	at au.org.ala.scatterplot.Scatterplot.<init>(Scatterplot.java:132)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
```

**Comment by adam-collins** [comment]
AreaReport is refactored.
